/*
 * Stream-Deck-friendly shortcut files.
 *
 * Plugin generates one .vbs per dockset under <config>/shortcuts/.
 * Each .vbs creates a marker file in <config>/triggers/.
 * Plugin watches triggers/ and processes incoming markers.
 *
 * Special shortcuts:
 *   _Cycle Next.vbs   -> writes "__cycle_next__.trigger"
 *   _Cycle Prev.vbs   -> writes "__cycle_prev__.trigger"
 */

#include "docksets-shortcuts.hpp"
#include "docksets-core.hpp"

#include <obs-module.h>
#include <plugin-support.h>

#include <QDir>
#include <QFile>
#include <QFileSystemWatcher>
#include <QFileInfo>
#include <QSet>
#include <QStringList>
#include <QTimer>
#include <QMetaObject>

#define TRIGGER_CYCLE_NEXT "__cycle_next__"
#define TRIGGER_CYCLE_PREV "__cycle_prev__"

static ShortcutsManager *g_instance = nullptr;

ShortcutsManager *ShortcutsManager::instance()
{
	if (!g_instance)
		g_instance = new ShortcutsManager();
	return g_instance;
}

ShortcutsManager::ShortcutsManager(QObject *parent) : QObject(parent) {}
ShortcutsManager::~ShortcutsManager() = default;

QString ShortcutsManager::shortcuts_dir() const
{
	QString base = DocksetCore::instance()->config_dir();
	QDir d(base);
	d.mkpath(QStringLiteral("shortcuts"));
	/* Absolute path — see triggers_dir for rationale. */
	return QDir(d.filePath(QStringLiteral("shortcuts"))).absolutePath();
}

QString ShortcutsManager::triggers_dir() const
{
	QString base = DocksetCore::instance()->config_dir();
	QDir d(base);
	d.mkpath(QStringLiteral("triggers"));
	/* Always return an ABSOLUTE path. obs_module_get_config_path in
	 * portable-mode OBS returns relative paths which break VBS-shortcuts
	 * when launched from Stream Deck / wscript with a different working dir. */
	return QDir(d.filePath(QStringLiteral("triggers"))).absolutePath();
}

QString ShortcutsManager::safe_filename(const QString &name) const
{
	QString s = name;
	for (QChar &c : s) {
		if (!c.isLetterOrNumber() && c != '_' && c != '-' && c != ' ')
			c = '_';
	}
	return s.trimmed();
}

void ShortcutsManager::initialize()
{
	if (m_initialized)
		return;

	/* Force directory creation */
	const QString sdir = shortcuts_dir();
	const QString tdir = triggers_dir();
	(void)sdir;

	m_watcher = new QFileSystemWatcher(this);
	m_watcher->addPath(tdir);
	connect(m_watcher, &QFileSystemWatcher::directoryChanged,
		this, &ShortcutsManager::on_triggers_changed);

	connect(DocksetCore::instance(), &DocksetCore::docksetsChanged,
		this, &ShortcutsManager::rebuild_shortcuts);

	rebuild_shortcuts();

	/* In case there are leftover triggers from a previous session, sweep them now. */
	QTimer::singleShot(500, this, [this]() { process_pending_triggers(); });

	m_initialized = true;
	obs_log(LOG_INFO, "shortcuts: ready (shortcuts at %s)",
		shortcuts_dir().toUtf8().constData());
}

void ShortcutsManager::shutdown()
{
	/* Robust cleanup: explicitly remove watch paths, disconnect signals
	 * and delete synchronously. deleteLater() during shutdown is unsafe
	 * because the event loop is winding down. */
	if (m_watcher) {
		QStringList paths = m_watcher->directories();
		if (!paths.isEmpty())
			m_watcher->removePaths(paths);
		paths = m_watcher->files();
		if (!paths.isEmpty())
			m_watcher->removePaths(paths);
		QObject::disconnect(m_watcher, nullptr, this, nullptr);
		delete m_watcher;
		m_watcher = nullptr;
	}
	/* Also detach from DocksetCore signals so we don't get callbacks
	 * during destruction. */
	QObject::disconnect(DocksetCore::instance(), nullptr, this, nullptr);
	m_initialized = false;
}

void ShortcutsManager::write_dockset_shortcut(const QString &dockset_name)
{
	QString sdir = shortcuts_dir();
	QString tdir = triggers_dir();
	QString safe = safe_filename(dockset_name);
	if (safe.isEmpty())
		return;

	QString trigger_path = QDir::toNativeSeparators(QDir(tdir).filePath(safe + QStringLiteral(".trigger")));
	/* VBS does NOT escape backslashes. Pass the path verbatim. */
	QString vbs;
	vbs += "' Auto-generated by Dynamic Docksets - loads a dockset by writing a trigger file.\r\n";
	vbs += "' Do not edit; the plugin re-generates this file on every dockset change.\r\n";
	vbs += "Set fso = CreateObject(\"Scripting.FileSystemObject\")\r\n";
	vbs += "trigger = \"" + trigger_path + "\"\r\n";
	vbs += "fso.CreateTextFile(trigger, True).Close\r\n";

	QString out_path = QDir(sdir).filePath(safe + QStringLiteral(".vbs"));
	QFile f(out_path);
	if (f.open(QIODevice::WriteOnly | QIODevice::Truncate)) {
		f.write(vbs.toUtf8());
		f.close();
	}
}

void ShortcutsManager::write_cycle_shortcuts()
{
	QString sdir = shortcuts_dir();
	QString tdir = triggers_dir();

	auto write_one = [&](const QString &filename, const QString &trigger_name) {
		QString trigger_path = QDir::toNativeSeparators(
			QDir(tdir).filePath(trigger_name + QStringLiteral(".trigger")));
		QString vbs;
		vbs += "' Auto-generated by Dynamic Docksets - cycle action.\r\n";
		vbs += "Set fso = CreateObject(\"Scripting.FileSystemObject\")\r\n";
		vbs += "trigger = \"" + trigger_path + "\"\r\n";
		vbs += "fso.CreateTextFile(trigger, True).Close\r\n";
		QString out_path = QDir(sdir).filePath(filename);
		QFile f(out_path);
		if (f.open(QIODevice::WriteOnly | QIODevice::Truncate)) {
			f.write(vbs.toUtf8());
			f.close();
		}
	};

	write_one(QStringLiteral("_Cycle Next.vbs"), QStringLiteral(TRIGGER_CYCLE_NEXT));
	write_one(QStringLiteral("_Cycle Prev.vbs"), QStringLiteral(TRIGGER_CYCLE_PREV));
}

void ShortcutsManager::rebuild_shortcuts()
{
	QString sdir = shortcuts_dir();
	if (sdir.isEmpty())
		return;

	QStringList names = DocksetCore::instance()->ordered_names();

	/* Build set of filenames we should keep. */
	QSet<QString> keep;
	for (const QString &n : names)
		keep.insert(safe_filename(n) + QStringLiteral(".vbs"));
	keep.insert(QStringLiteral("_Cycle Next.vbs"));
	keep.insert(QStringLiteral("_Cycle Prev.vbs"));

	/* Delete obsolete .vbs files (e.g. after rename/delete of a dockset). */
	QDir d(sdir);
	for (const QString &fn : d.entryList(QStringList() << QStringLiteral("*.vbs"), QDir::Files)) {
		if (!keep.contains(fn))
			QFile::remove(d.filePath(fn));
	}

	/* (Re)create current shortcuts. */
	for (const QString &n : names)
		write_dockset_shortcut(n);
	write_cycle_shortcuts();
}

void ShortcutsManager::on_triggers_changed(const QString &)
{
	/* Slight delay to let the trigger file finish being written. */
	QTimer::singleShot(50, this, [this]() { process_pending_triggers(); });
}

void ShortcutsManager::process_pending_triggers()
{
	QDir d(triggers_dir());
	const QStringList files = d.entryList(QStringList() << QStringLiteral("*.trigger"), QDir::Files);
	for (const QString &fn : files) {
		QString full = d.filePath(fn);
		QString base = QFileInfo(fn).baseName();

		/* Always delete the trigger first to avoid re-processing. */
		QFile::remove(full);

		if (base == QStringLiteral(TRIGGER_CYCLE_NEXT)) {
			DocksetCore::instance()->cycle_next();
			obs_log(LOG_INFO, "shortcut trigger: cycle next");
			continue;
		}
		if (base == QStringLiteral(TRIGGER_CYCLE_PREV)) {
			DocksetCore::instance()->cycle_prev();
			obs_log(LOG_INFO, "shortcut trigger: cycle prev");
			continue;
		}

		/* Find the dockset whose safe-filename matches this trigger basename. */
		QStringList names = DocksetCore::instance()->ordered_names();
		QString match;
		for (const QString &n : names) {
			if (safe_filename(n) == base) {
				match = n;
				break;
			}
		}
		if (match.isEmpty()) {
			obs_log(LOG_WARNING, "shortcut trigger '%s' did not match any dockset",
				base.toUtf8().constData());
			continue;
		}
		obs_log(LOG_INFO, "shortcut trigger: load '%s'", match.toUtf8().constData());
		DocksetCore::instance()->load(match);
	}
}
